main:
  title: main.title
  description: main.description
rss:
  title: フナイログ
  description: ガジェットやエンジニアリングがメインのライフログ
author:
  name: Ryota Ikezawa
links:
  github: https://github.com/paveg/blog-next-contentlayer
  instagram: https://www.instagram.com/funa1y
  twitter: https://twitter.com/paveg_
